// flow-typed signature: 74289cb9541567a0adfe0418b90942d9
// flow-typed version: <<STUB>>/eslint-config-xo-space_v^0.16.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-xo-space'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-xo-space' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-xo-space/browser' {
  declare module.exports: any;
}

declare module 'eslint-config-xo-space/esnext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-xo-space/browser.js' {
  declare module.exports: $Exports<'eslint-config-xo-space/browser'>;
}
declare module 'eslint-config-xo-space/esnext.js' {
  declare module.exports: $Exports<'eslint-config-xo-space/esnext'>;
}
declare module 'eslint-config-xo-space/index' {
  declare module.exports: $Exports<'eslint-config-xo-space'>;
}
declare module 'eslint-config-xo-space/index.js' {
  declare module.exports: $Exports<'eslint-config-xo-space'>;
}
